name: podcast_analytics
version: '1.0.0'
config-version: 2

profile: podcast_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations following Medallion Architecture
models:
  podcast_analytics:
    raw:
      +materialized: incremental
      +schema: raw
    validated:
      +materialized: incremental
      +schema: validated
    cleansed:
      +materialized: incremental
      +schema: cleansed
    analytics:
      +materialized: incremental
      +schema: analytics

# Seed configurations
seeds:
  podcast_analytics:
    +schema: cleansed
    cleansed_users:
      +column_types:
        user_id: varchar(50)
        signup_date: date
        country: varchar(10)

# Variables for file paths
vars:
  data_load_path: 'data'
