name: podcast_analytics
version: '1.0.0'
config-version: 2

profile: podcast_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations following Medallion Architecture
models:
  podcast_analytics:
    # Raw models (Bronze layer) - materialized as incremental for performance
    raw:
      +materialized: incremental
      +schema: raw
    validated:
      +materialized: incremental
      +schema: validated
    # Cleansed models (Silver layer) - materialized as tables for deduplication
    cleansed:
      +materialized: table
      +schema: cleansed
    # Analytics/marts models (Gold layer) - materialized as incremental for performance
    analytics:
      +materialized: incremental
      +schema: analytics

# Seed configurations
seeds:
  podcast_analytics:
    +schema: cleansed
    users:
      +column_types:
        user_id: varchar(50)
        signup_date: date
        country: varchar(10)

# Variables for file paths
vars:
  events_json_path: 'data/*.json'
  data_load_base_path: 'data'
