version: 2

models:
  - name: dim_users
    description: "Dimension table containing user information"
    columns:
      - name: user_id
        description: "Unique identifier for a user"
        tests:
          - unique
          - not_null
      - name: signup_date
        description: "Date when the user signed up"
        tests:
          - not_null
      - name: country
        description: "Country where the user is located"
        tests:
          - not_null

  - name: dim_episodes
    description: "Dimension table containing episode information"
    columns:
      - name: episode_id
        description: "Unique identifier for an episode"
        tests:
          - unique
          - not_null
      - name: podcast_id
        description: "Identifier for the podcast this episode belongs to"
        tests:
          - not_null
      - name: title
        description: "Title of the episode"
        tests:
          - not_null
      - name: release_date
        description: "Date when the episode was released"
        tests:
          - not_null
      - name: duration_seconds
        description: "Duration of the episode in seconds"
        tests:
          - not_null
      - name: load_at
        description: "Timestamp when the data was loaded into the system"
        tests:
          - not_null
      - name: filename
        description: "Source filename for auditing and data lineage"
        tests:
          - not_null

  - name: fact_user_interactions
    description: "Fact table containing user interaction events"
    columns:
      - name: interaction_id
        description: "Auto-incrementing primary key for interactions"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to dim_users. Cannot be null, orphaned interactions are not permitted in this model"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_users')
                field: user_id
      - name: episode_id
        description: "Foreign key to dim_episodes. Cannot be null, orphaned interactions are not permitted in this model"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_episodes')
                field: episode_id
      - name: event_type
        description: "Type of interaction event"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['play', 'pause', 'seek', 'complete']
      - name: timestamp
        description: "When the interaction occurred"
        tests:
          - not_null
      - name: duration
        description: "Duration in seconds (for play/complete events)"
        # Duration can be null for pause/seek events
        
      - name: load_at
        description: "Timestamp when the data was loaded into the system"
        tests:
          - not_null
          
      - name: filename
        description: "Source filename for auditing and data lineage"
        tests:
          - not_null

  - name: question_1_top_completed_episodes
    description: "Analysis Question 1: The top 10 most completed episodes in the past 7 days"
    config:
      meta:
        analysis_question: "What are the top 10 most completed episodes in the past 7 days?"
        parameters:
          - name: analysis_end_date
            description: "End date for the 7-day analysis window"
            default: "2024-01-07"
            example: "2024-01-05"
    columns:
      - name: episode_id
        description: "Unique identifier for the episode"
        tests:
          - not_null
      - name: title
        description: "Episode title"
        tests:
          - not_null
      - name: podcast_id
        description: "Podcast identifier"
        tests:
          - not_null
      - name: completion_count
        description: "Number of times the episode was completed in the analysis period"
        tests:
          - not_null
      - name: release_date
        description: "When the episode was originally released"
        tests:
          - not_null
      - name: duration_seconds
        description: "Episode duration in seconds"
        tests:
          - not_null

  - name: question_2_avg_listen_through_rate_by_country
    description: "Analysis Question 2: Average listen-through rate (completion duration/episode duration) by country"
    config:
      meta:
        analysis_question: "What is the average listen-through rate by country?"
        calculation: "completion_duration / episode_duration_seconds, averaged by country"
    columns:
      - name: country
        description: "Country where users are located"
        tests:
          - not_null
      - name: avg_listen_through_rate
        description: "Average ratio of completion duration to episode duration for the country"
        tests:
          - not_null
      - name: total_completions
        description: "Total number of completion events used in the calculation"
        tests:
          - not_null
